### ISSUE TITLE
Header - Make the address go beside the Find/Become buttons

### ISSUE THREAD

**Issue by ianfader** [CCI-Studios/Ultra-Sunrooms#41]
![screen shot 2016-05-02 at 11 54 13 am](https://cloud.githubusercontent.com/assets/8989188/14959302/af98550e-105c-11e6-8153-8804218c4ecd.png)

**Comment by hemantcci** [comment]
![screen shot 2016-05-04 at 8 59 56 am](https://cloud.githubusercontent.com/assets/8450186/15014936/eb4a7b24-11d6-11e6-81f0-dd1c117f25ff.png)

This is what you meant ?

**Comment by ianfader** [comment]
Can the address go on the other side? So it would be address then find/become buttons.
